#+Title: Swift: The /Fast/ TeX Automation Tool
#+Author: Sean Allred
#+Email: tex@seanallred.com

This project was and continues to be heavily inspired by cereda/arara.
It hopes to be compatible with arara in its declaration of rules, but
it also hopes to add new features:

- Directives can be run in parallel
  #+begin_src latex
  % swift: {{
  % swift: biber
  % swift: makeindex
  % swift: }}
  #+end_src
- Rules can be supplied in a directory specified via directive:
  #+begin_src latex
  % swift: @ path/to/rules
  % swift: @ path/to/more/rules
  #+end_src

This is an alpha-level development repository and its history is
subject to rewrite to keep things tidy until further notice.  Pull
requests are of course welcome (if potentially unwarranted at this
stage), but please raise a related issue before doing so.  This will
allow discussion at this infant stage and, more importantly, will
server as a red-flag for me if I ever need to rewrite the history.

Note that, with the above, there are many files in this repository
that serve as notes/reminders and many that simply server no further
purpose.  The files that I /am/ working with include
- =Process.[ch]pp= :: encapsulate a single-threaded process
- =ProcessGroup.[ch]pp= :: multi-threading support
- =test.cpp= :: driver
- =makefile= :: build

* License
Taking its cue from cereda/arara, this project is released under the
New BSD license, a GPL-compatible free software license.
